NearNodeFlash/nnf-deploy

config/repositories.yaml
config/systems.yaml

In KJPLAT-541 the lustre-csi-driver is being sanitized of any references to
rabbit or nnf. Other rabbit repos must be adjusted for this.

RABSW-963 Adjust rabbit repos for nnf-sanitized lustre-csi-driver

---

main.go

Use runCommand in the InstallCmd.Run() method, to ease debugging of daemon
installs.

RABSW-961 nnf-deploy: use runCommand in the InstallCmd.Run() method

---

config/repositories.yaml

Update the repository file to find a "kind" overlay for lustre-csi-driver.

RABSW-974 Let the lustre-csi-driver deployment default to lustre-capable

---

main.go

Failure to remove causes install to not install because of this snippet in the `Install()` call
```go
if linux.isInstalled() {
return installAction + failed, ErrAlreadyInstalled
}
```
Signed-off-by: Nate Roiger <nate.roiger@hpe.com>

Use daemon removal option to properly remove existing service prior install

---

main.go

Use quite mode (-q) when retrieving remote md5sum, thereby suppressing the connection message present on some systems (rabbit-dev-cn-*)
```
$ ssh rabbit-dev-cn-02 "md5sum /usr/bin/nnf-dm"
#=====================================================================
#
#=====================================================================
9bba9c591945046c7fb8aaa7c810722d  /usr/bin/nnf-dm
```
```
$ ssh -q rabbit-dev-cn-02 "md5sum /usr/bin/nnf-dm"
9bba9c591945046c7fb8aaa7c810722d  /usr/bin/nnf-dm
```
Signed-off-by: Nate Roiger <nate.roiger@hpe.com>

Use quite mode when retrieving remote md5sum

---

config/repositories.yaml
config/systems.yaml

Modifies the necessary config files to support the [config file restructuring PR](https://github.com/HewlettPackard/lustre-csi-driver/pull/19) arriving in the lustre-csi-driver repository.
Signed-off-by: Nate Roiger <nate.roiger@hpe.com>

Support for refactored lustre-csi-driver repo

---

config/systems.yaml
kind.sh

Always create the kind-config; even if it already exists - this ensures that the systems.yaml matches the config.

Always use new kind config, update systems.yaml

---

resources.sh

resource.sh script that provides some useful commands for operating on DWS and NNF resources
```
Run various debug commands against an NNF cluster
Usage: ./resources.sh COMMAND [ARGS...]
Commands:
get-all [OUTPUT-FORMAT]             Run 'kubectl get ...' against all DWS and NNF related resources
with the desired OUTPUT-FORMAT (default: yaml)
remove-finalizers                   Remove the finalizers in all DWS and NNF related resources.
WARNING: Can result in possible system corruption. Use at your
own risk.
```

resource.sh script

---

test/internal/system.go
test/internal/system_test.go
test/suite_test.go

Adds a reservation mechanism to ensure no system test runs on a currently reserved system. 
To reserve a system, create a namespace in your name. The regexp is defined to take first name and last name combinations like "nate", "natet", "nate-thornton", "nate-with-any-annotation". The important thing is it _must_ start with your name; "hey-this-is-nate" would not qualify.
To run the test suite against a reserved system, use the `--ignore-reservation` flag.
If a system is reserved (as it current is as of this writing), you'll see the test suite abort with a message like
`[ABORTED] System is current reserved by 'Matt Richerson'`

Nnf test system reservation

---

config/daemons.yaml

The clientmount and nnf-dm daemons have their own ServiceAccounts now. Use the secrets from these ServiceAccounts for the token and cert files.

RABSW-1150: Use new daemon ServiceAccounts

---

config/daemons.yaml
main.go

The HA cluster requires a fencing agent that can communicate with kubernetes. Copy the cert and token to the compute nodes during the "nnf-deploy install" step.

RABSW-1025: Deploy Cert and Token for nnf fencing agent

---

.gitignore
main.go
release_manifest.yaml

Add new subcommands to the nnf-deploy tool to manage releases of the Rabbit software components.
Four new subcommands were introduced:
- nnf-deploy release list - Show releases that nnf-deploy is aware of
- nnf-deploy release info - Show information about a release
- nnf-deploy release create - Create a new release based on the commits the submodules are currently set to
- nnf-deploy release set - Set the current release. This will checkout the correct commit in all the submodules
Release information is storage in the release_manifest.yaml file in the nnf-deploy repo. A separate .release_manifest.yaml file is kept locally as well.

RABSW-1152: Manage module versions through releases

---

.github/workflows/int-test.yaml
.github/workflows/main.yaml
Makefile
config/config.go
config/config_suite_test.go
config/config_test.go
config/systems.yaml
go.mod
go.sum
main.go

* Add checks for:
* duplicate system names
* duplicate aliases
* missing overlays
* missing workers
* duplicate rabbit node names
* duplicate compute node names (in a system)
* Add supporting functions to make system config eaiser to test
* Add unit tests for config.go
* Add Makefile to run tests locally
* Add GitHub workflow to run tests
* Fixed incorrectly named worker node for htx-2
* Fixed bug in main.go that prints error output twice

Add verification to System Configuration (systems.yaml)

---

config/config.go
config/repositories.yaml
main.go

Create a generic way to handle third-party services like cert-manager and mpi-operator.
Add a section to repositories.yaml to handle the third-party services.  Allow a "wait command" to be specified, so we can wait for the webhook on a service like cert-manager.

Handle third-party services

---

Makefile

Allow make to determine whether "nnf-deploy" is out of date with "main.go".

Improve main.go dependency

---

config/repositories.yaml
go.mod
go.sum

Pull in lustre-fs-operator CRD fix for kubectl 1.27.

Fix for kubectl version 1.27

---

test/int_test.go

- Add useful labels to container tests (e.g. mpi)
- Fix the storage variables to only use underscores
- Remove the root tests (for now)

int-test: fix container tests

---

config/config.go
config/daemons.yaml
main.go
test/int_test.go

**Note**: The existing clientmount services on compute nodes will need to be removed. See below.
The nnf-dm and client-mount daemons were being built manually in nnf-deploy rather than making use of their Makefiles. This was causing the versions to sit at 0.0.0 rather than the built in versioning. provided by the Makefiles.
In order to support this change, the client-mount service had to be renamed to clientmountd in dws. The binary built by the Makefile and the RPMs is named clientmountd, so nnf-deply looks for an clientmountd.service file - which wouldn't exist without the rename.
Any compute node running the old version will need to remove the service before the renamed service will work properly.
At LLNL, this should not be an issue since they are already using the clientmountd …

Build daemons using their makefiles

---

main.go

Let `nnf-deploy deploy` execute the same way on KIND as it does on hardware.

Deploy in KIND as on hardware

---

config/repositories.yaml

Cert-manager 1.12.0 and 1.13.0 were big releases.  It's time to catch up.

Move to cert-manager 1.13.1

---

config/audit-policy.yaml

The .objectRef.name is already printed with the .requestURI.

Reduce the size of the audit log summary

---

config/service-monitor-selector.yaml
deploy-prometheus.sh

Introduce a deploy-prometheus.sh script that can install the prometheus-community/kube-prometheus-stack helm chart.  Include a file that overrides the ServiceMonitor selector in the chart's values,yaml.  This selector inserts a label that is common across the ServiceMonitor resources in the DWS and NNF repos.

Requirements for Prometheus

---

cmd/main.go
config/config.go
config/systems.yaml

The texas system's compute nodes cannot hit the k8s cluster with the public facing IP like our other systems.
This change adds additional configuration for k8s host and port that is fed into the daemons' configuration so they are able to talk to the cluster from the computes using a separate host/port, if necessary.

Add k8sHost + k8sPort to systems config

---

config/daemons.yaml

clientmountd moved from dws to nnf-sos. Update the daemons.conf file to point to the new repo and use the correct service account.

Use clientmountd in nnf-sos

---

cmd/main.go
config/config.go
config/daemons.yaml

* Added Environment field to daemons to support environment variables in
systemd overrides file
* Fixed an issue with line endings in the systemd overrides file that caused
the first Environment field to be ignored
* Added tunings for both daemons

Add daemon env var support; tune daemon garbage collection, max procs, & HTTP2 health check

---

cmd/main.go
config/config.go
config/daemons.yaml

Both nnf-dm and clientmountd default to the system hostname if these options are not provided, so there is no need to keep providing them via the systemd service file. LLNL does not plan on setting these command line options to make configuration easier on their end - we should follow suit.
The formatting for the overrides file has been cleaned up a bit as well.

Remove --nnf-node-name and --node-name from service files

---

cmd/main.go

Use 'kubectl create' for this resource so that k8s does not create the "last-applied-configuration" annotation.  This resource is not being updated by any controller, and the admins can be taught to update it with 'kubectl replace' so that annotation is never needed.
This resource can be quite large on a big system and the "last-applied-configuration" annotation that is created by 'kubectl apply' can exceed the allowed size of an annotation.

Use kubectl create for SystemConfiguration resource

---

.github/workflows/handle_release_tag.yaml
Makefile
tools/collect-manifests.sh

If a pod is on a host that cannot be reached, then any attempt to delete the namespace will hang.  So change this to preserve the namespace and leave that pod for k8s to cleanup when it can.
Add getopts to collect-manifests.sh, and update the tool to filter the namespace out of the manifests it collects for ArgoCD. Make the tool all-in-one so it collects the manifests and also makes the tarball; that should make it less cumbersome in a manual situation.

Preserve the service namespace during undeploy

---

.gitignore
tools/collect-manifests.sh

When unpacking the manifest over an existing gitops repo, it'll be obvious when there has been a CRD update.

Place CRDs in their own manifest

---

Readme.md

Problem: the `kind.sh` script was moved to the `tools` subdirectory but the path was not updated in the README.
Fix the path.

README: fix broken path

---

cmd/main.go

This suppresses the "not found" error when you undeploy a system that is already undeployed.

Be quiet if SystemConfiguration does not exist at undeploy time

---

config/config.go

Protect against the case where there are no externalComputeNodes.
Otherwise the []interface{} conversion fails.

Fix for no externalComputeNodes

---

.github/workflows/handle_release_tag.yaml
.gitignore
Makefile
tools/collect-manifests.sh

When collecting a manifest, specify whether it is being collected for KIND or for hardware, and run the edit-image makefile target in each submodule to ensure that the desired type of manifest will be generated. Read the overlays list out of config/systems.yaml to find the appropriate overlay in each submodule for the desired type of manifest.
Add both manifests to the release artifacts.

Collect separate manifests for hardware vs KIND

---

Makefile

```
$ make manifests
tools/collect-manifests.sh -s kind -d $PWD/release-manifests-kind -t $PWD/manifests-kind.tar
The directory /Users/blakedevcich/src/rabbit/nnf-deploy/release-manifests-kind already exists
make: *** [manifests] Error 1
```

Clean before make manifests, otherwise it will fail

---

.gitignore
Readme.md
cmd/main.go
config/config.go
config/helm-values/argocd.yaml
config/overlay-legacy.yaml-template
config/repositories.yaml

The `nnf-deploy init` command will install ArgoCD via helm. The user must have the helm CLI installed and the argoproj helm repo added to their local cache.
The command will no longer install cert-manager, mpi-operator, lustre-csi-driver, or lustre-fs-operator at init time. Those will be handled from the ArgoCD gitops repo.
To restore legacy init behavior, copy the config/overlay-legacy.yaml-template file to ./overlay-legacy.yaml.

Switch nnf-deploy init to install ArgoCD

---

config/audit-policy.yaml

Adjust the KIND audit policy to log only metadata, to reduce the size of the audit log.

Set audit policy level to metadata

---

tools/default-nnfstorageprofile.sh

Problem: the 'placeholder' nnfstorageprofile was renamed to 'template' by PR #152.
Fix an old reference to 'placeholder'.

deploy: fix reference to renamed storageprofile

---

Makefile
tools/git-version-gen

Send nnf-deploy's own git-version-gen output, representing the nnf-deploy release, or 0.0.0-thingy if it's master, to the submodules so they can add it as a label on the items they add to their manifests.

Add version labels to release manifest items

---

tools/collect-flux-dms.py

This tool pulls NnfDataMovement resources that are dumped to the
flux-coral2-dws journal and runs stats on them.
The output is formatted in json for easy parsing.

Add collect-flux-dms.py

---

tools/release-all.sh

The git-log command does not have a --no-pager option, so send things through the cat(1) command to suppress the paging when there a lots of commits to display.

git-log without paging

---

tools/release-all/release-all.sh

Originally, this tool didn't fuss if these files were the only thing out of date. However, this has allowed some merge conflicts to appear.

Require that go.mod, go.sum, vendor/modules.txt be up to date

---

tools/release-all/release-all.sh

The 'pipefail' setting was too aggressive.

Check for yq in release-all

---

tools/crd-bumper/crd-bumper.py
tools/crd-bumper/pkg/controllers.py
tools/crd-bumper/pkg/make_cmd.py

Allow a repo to have a file named "crd-bumper.yaml" where it can specify some repo-specific info.

Support repo-specific crd-bumper config

---

tools/crd-bumper/crd-bumper.py
tools/crd-bumper/pkg/controllers.py
tools/crd-bumper/pkg/conversion_gen.py

Allow the repo-local config file to specify a comma-separated list of directories of Kustomize config files that have references to the API and that must be updated to the new hub version so that ArgoCD can sync them.

Allow kustomize examples to be bumped by crd-bumper

---

tools/crd-bumper/README.md
tools/crd-bumper/pkg/go_cli.py
tools/crd-bumper/pkg/make_cmd.py
tools/crd-bumper/pkg/vendoring.py
tools/crd-bumper/vendor-new-api.py

The vendor-new-api.py tool is a companion tool to crd-bumper. After crd-bumper has been used to create a new API version, the vendor-new-api tool can be used to vendor that into other repositories that consume the API.

A tool to vendor a new API into a consumer repo

---

tools/crd-bumper/README.md
tools/crd-bumper/pkg/vendoring.py
tools/crd-bumper/vendor-new-api.py

Change the vendor-new-api.py script to only vendor a new API for the latest API in the target repo. Old API versions may have embedded structs from a vendor API, and we don't want them to change.
Also, add an option to specify which version of the vendor API to "go get".

Ignore old versions when vendoring new API

---

tools/crd-bumper/crd-bumper.py
tools/crd-bumper/pkg/conversion_gen.py
tools/crd-bumper/pkg/create_apis.py
tools/crd-bumper/pkg/hub_spoke_util.py
tools/crd-bumper/pkg/vendoring.py
tools/crd-bumper/unserve.py
tools/crd-bumper/vendor-new-api.py

Adjust vendor-new-api.py so it can vendor into the nnf-integration-test repo. This relies on a new crd-bumper.yaml file in that repo to give some hints.
Refactor code that checks whether an API is a hub or a spoke.
Refactor code that references the crd-bumper.yaml file. This simplifies the use of the object that holds the content of that file.
Reformat code with 'black'.

Allow vendoring into nnf-integration-test repo

---

tools/kind.sh

On the docker host, the /tmp/nnf dir is expected to be mounted into each docker container as /mnt/nnf.
The k8s pods will add volume mounts for /mnt/nnf and will place their mock devices and filesystems there.

Enable mock filesystems in KIND

---

cmd/main.go

Allow dry-run to run some things that don't modify the target node, and add a dry-run-always to prevent even that much.
Add some vertical whitespace to the output to make it easier to follow.

Enhance dry-run with install

---

tools/release-all/README.md
tools/release-all/release-all.sh

When making a release, some repos will refer to the latest release of an earlier repo. This means each repo must be fully released before the release of the next repo can begin. So for some of these commands there's no point in allowing multiple repos to be specified.

Limit some release-all commands to only one repo

---

cmd/main.go
config/config.go
config/libraries.yaml

The client token is not needed, so don't install it on the compute node.
Additionally, ensure the destination pathing is available on the compute
node by running `mkdir` first when needed.

Remove client token; only deploy client cert

---

tools/release-all/release-all.sh

In the current example, nnf-sos must vendor two API versions from DWS to get two versions of the ResourceError. In general, we still expect this to be an unusual situation, so this is still treated as an exception and the user must use -M to allow it.

Let release-all allow multiple API versions from a single module.

---

tools/crd-bumper/pkg/git_cli.py
tools/crd-bumper/pkg/unserve.py
tools/crd-bumper/re-serve.py

It's possible that after marking an API as unserved and doing a release, there will be a need to follow-up that release with a variation of it that does serve that API. And maybe the commit that did the "unserve" step is buried under other things and is not easily reverted. In that case, use the `re-serve.py` tool.

Mark an unserved API as served

---

tools/crd-bumper/pkg/vendoring.py
tools/crd-bumper/vendor-new-api.py

This ought to be an unusual case, so you have to explicitly ask for it.

Allow vendor-new-api to vendor multi API versions from one repo

---

tools/release-all/final-release-notes.sh
tools/release-all/release-all.sh

A release of the docs should have a reference to the matching nnf-deploy release, so the two are kept in sync.

release-all: Update the docs with the nnf-deploy release
