NearNodeFlash/nnf-deploy

main.go
Signed-off-by: Nate Roiger <nate.roiger@hpe.com>
=> Use compression with scp command to speed up installs

Readme.md
Document the behavior of the update.sh command.  Document how to set a
submodule to a specific version or branch.
=> RABSW-989 document the update.sh command and how to control submodules

main.go
=> Handle k8s config file Contexts

main.go
=> Update dws & nnf-dm to latest, convert install to use SA secret directly

main.go
=> Add '--no-build' option to the install command

Readme.md, kind.sh, main.go
=> Remove the DWS node selector label.

test/int_test.go, test/internal/internal.go, test/internal/options.go
- Test duplication infrastructure (simple tests only, nothing too complex)
- Duplicate XFS test
=> Duplicate test infrastructure. XFSx5 test

test/suite_test.go
Using the SpecContext was not the right approach - for some reason that is never in a failed state. This uses a custom failure handler instead.
=> Fix for system not going into triage on failure

common.sh, kind.sh, main.go
Remove any use of the cray.nnf.manager label.  Anything that was relying on that will now go to any available untainted worker.
Update the submodules.
=> Initialize a KIND cluster with the same tool used for a real Rabbit

config/audit-policy.yaml, kind.sh
Define an audit policy for the Rabbit resources.
Enable audit logging for the KIND kube-apiserver.
=> Enable k8s audit logging in KIND

main.go, test/int_test.go, test/internal/internal.go, test/internal/options.go, test/internal/states.go, test/suite_test.go
int-test and the deployed SystemConfiguration were still using dwsv1alpha1
=> Use dwsv1alpha2

config/audit-policy.yaml
Update the DWS API group in the kube-apiserver audit_policy config.
=> Move DWS from HewlettPackard/dws to DataWorkflowServices/dws

cmd/main.go, config/repositories.yaml, config/systems.yaml
In nnf-sos, the default storage and container profiles are deployed
separately from the default configuration via `examples`.
In order to overlay on top of the examples, we must add the ability to
get the examples overlay separately and pass it through to the makefile
via OVERLAY_EXAMPLES env var.
=> Add examples-htx overlay to htx

config/systemconfiguration-htx-tds.yaml
I added the config/systemconfiguration-htx-tds.yaml for the texas system here as well.
=> Update the system configuration for texas and the submodules

config/repositories.yaml
=> Use latest released nnf-mfu

cmd/main.go
The nnf-sos SystemConfiguration controller is now responsible for adding the taints and labels to the rabbit nodes. Remove the label/taint code from nnf-deploy.
=> Let the SystemConfiguration controller add taints and labels to rabbits

tools/kind.sh
The script was calling itself and if you did this in the root directory
(now that `kind.sh` lives in `tools/`), it can't find `kind.sh`.
This just uses functions instead. There's still an issue with calling
`./nnf-deploy init` if you `cd tools/` first, but I'm ignoring that for
now.
=> kind.sh: fix reset

config/systemconfiguration-htx-tds.yaml
Add the computes and rabbit for chassis 1.
=> Add chassis1 to the configuration

config/systemconfiguration-htx-1.yaml, config/systemconfiguration-htx-tds.yaml, config/systemconfiguration-kind.yaml
The list of compute node names is already found within the spec.StorageNodes array. By having the names in just one array, rather than two, that ought to help reduce errors.
However, the main problem was this: The spec.ComputeNodes array can account for up to 75% of the size of the resource on a large cluster.  This has caused problems for 'kubectl apply' (client-side-apply) when it creates the "last-applied-configuration" annotation for the resource, with the serialized version of the resource exceeding the maximum allowed size of an annotation.
Add spec.ExternalComputeNodes to contain a list of compute nodes that are not directly matched with any of the nodes in the StorageNodes list.
=> Remove the ComputeNodes array from SystemConfiguration

cmd/main.go, tools/default-nnfstorageprofile.sh
Clone nnf-sos's NnfStorageProfile/placeholder resource to create a default storage profile for the system.
=>  Create a default NnfStorageProfile resource

tools/kind.sh
Upgrade to 1.29.2 and run shellcheck.
=> Upgrade kindest/node to v1.29.2

tools/release-all.sh
Detect the case when a release is being created from submodules that are not released.
=> Let the release phase verify that any submodules have been released.

tools/release-all.sh
Also, when the release branch is already pushed and is being fetched, re-run the merge and submodule verifications.
=> Update released submodules even when they do not have conflicts.

tools/release-all.sh
Add --abbrev=0 to any git-describe so we always get the unadorned tag.
=> Allow tag-release to be idempotent

tools/collect-manifests.sh
Add the release version to the manifest tarball.
=> Let collect-manifests record the release version

config/repositories.yaml
=> Release v0.1.10

tools/release-all/README.md, tools/release-all/final-release-notes.sh
This tool will update the nnf-deploy "What's Changed" text for the release. The new text will include the release notes from all submodules that contained changes in this release.
=> A tool to generate final release notes

tools/kind.sh
Also, set the indentation consistent at 4 spaces.
=> Upgrade kindest/node to 1.29.8

config/repositories.yaml
Nnf-dm now has overlays, so add that to its repository config.
=> Let nnf-deploy find overlays for nnf-dm

tools/kind.sh
In docker-desktop, I had to increase some Resources:
I increased the memory limit from 8GB to 12GB, and the virtual disk limit from 64GB to 72GB.
=> Upgrade to kindest/node v1.31.2

tools/release-all/release-all.sh
If a release branch PR has been accidently merged manually rather than using the "-P merge-pr" option, then a subsequent "-P tag-release" will fail to find the expected text in the merge PR.
This adds a "-x" option that can be used to help release-all in that case, to give it the release name that it was expecting to find in the merge PR.
=> Allow release-all to handle an accidental manual merge

cmd/main.go
Refactor the InstallCmd.Run() method. In the next step I will be creating another 'enumerateXXX' loop for the copy-offload library/header.
=> Refactor nnf-deploy install

tools/release-all/final-release-notes.sh
While collecting the release notes from each of nnf-deploy's submodules, first update that submodule's release notes with the submodule's list of active APIs.
=> Add per-submodule active API versions to release notes

config/repositories.yaml
=> Release v0.1.18

config/repositories.yaml
=> Release v0.1.20
